export const ADD_APPLES_TO_BASKET_REQUEST = 'ADD_APPLES_TO_BASKET_REQUEST';
export const ADD_APPLES_TO_BASKET_SUCCESS = 'ADD_APPLES_TO_BASKET_SUCCESS';
export const ADD_APPLES_TO_BASKET_ERROR = 'ADD_APPLES_TO_BASKET_ERROR';

export const FALL_APPLES_REQUEST = 'FALL_APPLES_REQUEST';
export const FALL_APPLES_SUCCESS = 'FALL_APPLES_SUCCESS';
export const FALL_APPLES_ERROR = 'FALL_APPLES_ERROR';
